locale: "uk"
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

media_library:
  name: uploadcare

collections:
  - name: "schedule"
    label: "Розклад"
    files:
      - file: "content.json"
        label: "Редагування розкладу"
        name: "schedule"
        fields:
          - label: "Новояворівськ (Робочі дні)"
            name: "novoyavorivsk"
            widget: "list"
            fields:
              - {label: "Дата", name: "date", widget: "string"}
              - {label: "Вільні години", name: "hours", widget: "list"}
          - label: "Івано-Франкове (Робочі дні)"
            name: "ivano_frankove"
            widget: "list"
            fields:
              - {label: "Дата", name: "date", widget: "string"}
              - {label: "Вільні години", name: "hours", widget: "list"}